version: '3.8'

services:
 web:
 # Build the dockerfile each run
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  # Makes a volume in the CT /app to local dir ./
  # This enables my code to update the app code in the container
  - ./:/app
  env_file: .env

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: